//
//  FrameworkAdapter.swift
//  
//
//  Created by Vladislav Gushin on 26.10.2023.
//

import Foundation
import VDEVEditorFramework

public typealias VDEVMediaEditorSourceService = VDEVEditorFramework.VDEVMediaEditorSourceService
public typealias VDEVMediaEditorConfig = VDEVEditorFramework.VDEVMediaEditorConfig
public typealias VDEVMediaEditorViewModel = VDEVEditorFramework.VDEVMediaEditorViewModel
public typealias VDEVMediaEditorView = VDEVEditorFramework.VDEVMediaEditorView
public typealias StartMetaConfig = VDEVEditorFramework.StartMetaConfig
public typealias TemplatePack = VDEVEditorFramework.TemplatePack
public typealias VDEVDataBuilder = VDEVEditorFramework.VDEVDataBuilder
public typealias StickerItem = VDEVEditorFramework.StickerItem
public typealias EditorFilter = VDEVEditorFramework.EditorFilter
public typealias NeuralEditorFilter = VDEVEditorFramework.NeuralEditorFilter
public typealias NeuralConfig = VDEVEditorFramework.NeuralConfig
public typealias BlendingMode = VDEVEditorFramework.BlendingMode
public typealias CanvasTextStyle = VDEVEditorFramework.CanvasTextStyle
public typealias VDEVNetworkModuleConfigType = VDEVEditorFramework.VDEVNetworkModuleConfigType
public typealias VDEVMediaEditorSecurity = VDEVEditorFramework.VDEVMediaEditorSecurity
public typealias VDEVMediaEditorStrings = VDEVEditorFramework.VDEVMediaEditorStrings
public typealias VDEVMediaEditorButtonsCommonImages = VDEVEditorFramework.VDEVMediaEditorButtonsCommonImages
public typealias VDEVMediaEditorButtonsTypedImages = VDEVEditorFramework.VDEVMediaEditorButtonsTypedImages
public typealias VDEVMediaEditorButtonsTextEditingImages = VDEVEditorFramework.VDEVMediaEditorButtonsTextEditingImages
public typealias VDEVMediaEditorButtonsCurrentItemImages = VDEVEditorFramework.VDEVMediaEditorButtonsCurrentItemImages
public typealias VDEVAdjustmentsButtonsCommonImages = VDEVEditorFramework.VDEVAdjustmentsButtonsCommonImages
public typealias VDEVImageConfig = VDEVEditorFramework.VDEVImageConfig
public typealias VDEVNetworkModuleConfig = VDEVEditorFramework.VDEVNetworkModuleConfig
public typealias VDEVLogger = VDEVEditorFramework.VDEVLogger
public typealias VDEVMediaEditorResultSettings = VDEVEditorFramework.VDEVMediaEditorResultSettings
public typealias VDEVMediaResolution = VDEVEditorFramework.VDEVMediaResolution
public typealias VDEVMediaEditorSettings = VDEVEditorFramework.VDEVMediaEditorSettings
public typealias CombinerOutput = VDEVEditorFramework.CombinerOutput
public typealias ImageProcessorHelper = VDEVEditorFramework.ImageProcessorHelper
public typealias VDEVMediaEdititorCanvasSettings = VDEVEditorFramework.VDEVMediaEdititorCanvasSettings

public let kPlaceholders = VDEVEditorFramework.kPlaceholders
