query GetChallengeMeta($baseChallengeId: ID!) {
  baseChallenge(id: $baseChallengeId) {
    titleLocalized
    subtitleLocalized
    hasAttachedStickerPacks
    appAttachedEditorTemplate {
      isAttached
    }
  }
}
