query GetChallengeMeta($baseChallengeId: ID!) {
  baseChallenge(id: $baseChallengeId) {
    titleLocalized
    subtitleLocalized
    editorMetadata {
      hasAttachedMasks
      hasAttachedFilters
      hasAttachedTextures
      hasAttachedTemplates
      hasAttachedStickerPacks
      hasAttachedNeuralFilters
    }
  }
}
